const orchids = [
  {
    id: "1",
    name: "Taichung Beauty",
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image:
      "https://img4.thuthuatphanmem.vn/uploads/2021/06/04/hinh-nen-hoa-lan-dep-chat-luong-nhat_032302391.jpg",
    color: "Pink",
    numberOfLike: 192,
    origin: "Taiwan",
    category: "Cattleya",
  },
  {
    id: "2",
    name: "Dendrobium Kingianum",
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image:
      "https://img4.thuthuatphanmem.vn/uploads/2021/06/04/hinh-nen-hoa-lan-dep-va-doc-dao_032303237.jpg",
    color: "Purple",
    numberOfLike: 134,
    origin: "Australia",
    category: "Dendrobium",
  },
  {
    id: "3",
    name: "Phalaenopsis Amabilis",
    rating: 5,
    isSpecial: true,
    isNatural: true,
    image:
      "https://img2.thuthuatphanmem.vn/uploads/2018/12/09/gian-hoa-phong-lan-dep-nhat_111010540.jpg",
    color: "White",
    numberOfLike: 201,
    origin: "Indonesia",
    category: "Phalaenopsis",
  },
  {
    id: "4",
    name: "Cymbidium Ensifolium",
    rating: 3,
    isSpecial: false,
    isNatural: true,
    image:
      "https://img2.thuthuatphanmem.vn/uploads/2018/12/09/hinh-anh-chau-hoa-phong-lan-dep-nhat_111010737.jpg",
    color: "Green",
    numberOfLike: 98,
    origin: "China",
    category: "Cymbidium",
  },
  {
    id: "5",
    name: "Vanda Coerulea",
    rating: 4,
    isSpecial: true,
    isNatural: true,
    image:
      "https://img4.thuthuatphanmem.vn/uploads/2021/06/04/hinh-nen-hoa-lan-don-sac-dep-nhat_032303886.jpg",
    color: "Blue",
    numberOfLike: 156,
    origin: "India",
    category: "Vanda",
  },
  {
    id: "6",
    name: "Paphiopedilum Insigne",
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image:
      "https://th.bing.com/th/id/R.37bb734199987e6863fe5989d6aa534c?rik=8cF%2fG8l3%2fKKvnA&riu=http%3a%2f%2fxenangphuy.com%2fupload%2fimages%2flan-dep.jpg&ehk=i1jC%2fcR3onK0z8PJbWL76UR1VZlLvuuwARAqsulIGLM%3d&risl=&pid=ImgRaw&r=0",
    color: "Yellow",
    numberOfLike: 113,
    origin: "Nepal",
    category: "Paphiopedilum",
  },
  {
    id: "7",
    name: "Oncidium Sharry Baby",
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image:
      "https://img4.thuthuatphanmem.vn/uploads/2019/11/06/anh-hoa-lan-ho-diep-mau-tim_030011485.jpg",
    color: "Red/Brown",
    numberOfLike: 177,
    origin: "Hybrid",
    category: "Oncidium",
  },
  {
    id: "8",
    name: "Brassia Rex",
    rating: 3,
    isSpecial: false,
    isNatural: false,
    image:
      "https://th.bing.com/th/id/R.f58047fafe526e7abed098dd0dcaaa42?rik=zXXsrYFVDPLdvQ&riu=http%3a%2f%2f4.bp.blogspot.com%2f-X-JOWoXCDnk%2fVdqtkQaTqlI%2fAAAAAAAAD9M%2fN99gYtlXxdI%2fs1600%2fhinh-nen-hoa-phong-lan-dep-547.jpg&ehk=3tNnM3MOZRG7u%2bCqqo3XzY5N8CFF4EJyAX%2bg7gmbiVQ%3d&risl=&pid=ImgRaw&r=0",
    color: "Yellow/Spotted",
    numberOfLike: 89,
    origin: "Hybrid",
    category: "Brassia",
  },
  {
    id: "9",
    name: "Zygopetalum Mackayi",
    rating: 4,
    isSpecial: true,
    isNatural: true,
    image:
      "https://img4.thuthuatphanmem.vn/uploads/2021/06/04/hinh-nen-bong-hoa-lan_032300484.jpg",
    color: "Green/Purple",
    numberOfLike: 102,
    origin: "Brazil",
    category: "Zygopetalum",
  },
  {
    id: "10",
    name: "Laelia Anceps",
    rating: 5,
    isSpecial: false,
    isNatural: true,
    image:
      "https://img4.thuthuatphanmem.vn/uploads/2021/06/04/anh-nen-may-tinh-hoa-lan-trang_032300293.jpg",
    color: "Pink",
    numberOfLike: 145,
    origin: "Mexico",
    category: "Laelia",
  },
  {
    id: "11",
    name: "Epidendrum Radicans",
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image:
      "https://th.bing.com/th/id/R.1b245a92c61bff80185de03a60a8d57f?rik=5GiMcxVAlENrPQ&pid=ImgRaw&r=0",
    color: "Orange",
    numberOfLike: 87,
    origin: "Central America",
    category: "Epidendrum",
  },
  {
    id: "12",
    name: "Miltoniopsis Herralex",
    rating: 3,
    isSpecial: true,
    isNatural: false,
    image:
      "https://img4.thuthuatphanmem.vn/uploads/2021/06/04/anh-nen-canh-hoa-lan-dep_032256954.png",
    color: "White/Purple",
    numberOfLike: 110,
    origin: "Hybrid",
    category: "Miltoniopsis",
  },
  {
    id: "13",
    name: "Coelogyne Cristata",
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image:
      "https://tse4.mm.bing.net/th/id/OIP.B-LkyW0zI9YnsA8F3LCn1wHaEv?cb=iwc2&w=960&h=615&rs=1&pid=ImgDetMain",
    color: "White/Yellow",
    numberOfLike: 93,
    origin: "Himalayas",
    category: "Coelogyne",
  },
  {
    id: "14",
    name: "Masdevallia Veitchiana",
    rating: 5,
    isSpecial: true,
    isNatural: true,
    image:
      "https://vuonlan.net/wp-content/uploads/2018/03/lich-su-va-y-nghia-cua-loai-hoa-phong-lan-1.jpg",
    color: "Orange/Red",
    numberOfLike: 162,
    origin: "Peru",
    category: "Masdevallia",
  },
  {
    id: "15",
    name: "Sobralia Dichotoma",
    rating: 3,
    isSpecial: false,
    isNatural: true,
    image:
      "https://i.pinimg.com/originals/9a/00/38/9a0038fca02df4ee23e8b9d692ca3252.jpg",
    color: "Purple",
    numberOfLike: 74,
    origin: "South America",
    category: "Sobralia",
  },
  {
    id: "16",
    name: "Lycaste Aromatica",
    rating: 4,
    isSpecial: true,
    isNatural: true,
    image:
      "https://img4.thuthuatphanmem.vn/uploads/2021/06/04/hinh-nen-hoa-lan-xanh-dep-nhat_032306015.jpg",
    color: "Yellow",
    numberOfLike: 121,
    origin: "Mexico",
    category: "Lycaste",
  },
];

export default orchids;
